[package]
name = "pyterion"
version = "0.1.0-alpha"
edition = "2021"

[lib]
name = "pyterion"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.3", features = ["extension-module"] }
criterion = "0.3"
